---
- name: restart namenode
  become: true
  systemd:
    daemon_reload: true
    name: hadoop-hdfs-namenode
    state: restarted
  when:
    - not ansible_check_mode
- name: restart datanode
  become: true
  systemd:
    daemon_reload: true
    name: hadoop-hdfs-datanode
    state: restarted
  when:
    - not ansible_check_mode
- name: restart resourcemanager
  become: true
  systemd:
    daemon_reload: true
    name: hadoop-yarn-resourcemanager
    state: restarted
  when:
    - not ansible_check_mode
- name: restart nodemanager
  become: true
  systemd:
    daemon_reload: true
    name: hadoop-yarn-nodemanager
    state: restarted
  when:
    - not ansible_check_mode

- name: tag nn instance
  become: true
  shell: |
     EC2_INSTANCE_ID=`wget -q -O - http://169.254.169.254/latest/meta-data/instance-id`
     EC2_AVAIL_ZONE=`wget -q -O - http://169.254.169.254/latest/meta-data/placement/availability-zone`
     EC2_REGION="`echo \"$EC2_AVAIL_ZONE\" | sed -e 's:\([0-9][0-9]*\)[a-z]*\$:\\1:'`"
     /usr/bin/aws ec2 create-tags --region $EC2_REGION --resources $EC2_INSTANCE_ID --tags Key=jmx_exporter_nn,Value=installed
  when:
    - not ansible_check_mode

- name: tag dn instance
  become: true
  shell: |
     EC2_INSTANCE_ID=`wget -q -O - http://169.254.169.254/latest/meta-data/instance-id`
     EC2_AVAIL_ZONE=`wget -q -O - http://169.254.169.254/latest/meta-data/placement/availability-zone`
     EC2_REGION="`echo \"$EC2_AVAIL_ZONE\" | sed -e 's:\([0-9][0-9]*\)[a-z]*\$:\\1:'`"
     /usr/bin/aws ec2 create-tags --region $EC2_REGION --resources $EC2_INSTANCE_ID --tags Key=jmx_exporter_dn,Value=installed
  when:
    - not ansible_check_mode

- name: tag rn instance
  become: true
  shell: |
     EC2_INSTANCE_ID=`wget -q -O - http://169.254.169.254/latest/meta-data/instance-id`
     EC2_AVAIL_ZONE=`wget -q -O - http://169.254.169.254/latest/meta-data/placement/availability-zone`
     EC2_REGION="`echo \"$EC2_AVAIL_ZONE\" | sed -e 's:\([0-9][0-9]*\)[a-z]*\$:\\1:'`"
     /usr/bin/aws ec2 create-tags --region $EC2_REGION --resources $EC2_INSTANCE_ID --tags Key=jmx_exporter_rn,Value=installed
  when:
    - not ansible_check_mode

- name: tag nm instance
  become: true
  shell: |
     EC2_INSTANCE_ID=`wget -q -O - http://169.254.169.254/latest/meta-data/instance-id`
     EC2_AVAIL_ZONE=`wget -q -O - http://169.254.169.254/latest/meta-data/placement/availability-zone`
     EC2_REGION="`echo \"$EC2_AVAIL_ZONE\" | sed -e 's:\([0-9][0-9]*\)[a-z]*\$:\\1:'`"
     /usr/bin/aws ec2 create-tags --region $EC2_REGION --resources $EC2_INSTANCE_ID --tags Key=jmx_exporter_nm,Value=installed
  when:
    - not ansible_check_mode


