---
- name: restart namenode
  become: true
  systemd:
    daemon_reload: true
    name: hadoop-hdfs-namenode
    state: restarted
  when:
    - not ansible_check_mode
- name: restart datanode
  become: true
  systemd:
    daemon_reload: true
    name: hadoop-hdfs-datanode
    state: restarted
  when:
    - not ansible_check_mode
- name: restart resourcemanager
  become: true
  systemd:
    daemon_reload: true
    name: hadoop-yarn-resourcemanager
    state: restarted
  when:
    - not ansible_check_mode
- name: restart nodemanager
  become: true
  systemd:
    daemon_reload: true
    name: hadoop-yarn-nodemanager
    state: restarted
  when:
    - not ansible_check_mode
