- name: install prometheus
  hosts: all
  roles:
  - cloudalchemy.prometheus
  vars:
    prometheus_targets: {}
    prometheus_scrape_configs:
      - job_name: "prometheus"
        metrics_path: "{{ prometheus_metrics_path }}"
        static_configs:
          - targets:
              - "{{ ansible_fqdn | default(ansible_host) | default('localhost') }}:9090 "
      - job_name: "file_sd"
        file_sd_configs:
          - files:
              - "{{ prometheus_config_dir }}/file_sd/*.yml"
              - "{{ prometheus_config_dir }}/file_sd/*.json"
  tags:
    - ape_prometheus

- name: install grafana
  hosts: all
  roles:
  - cloudalchemy.grafana
  vars:
    grafana_security:
      admin_user: admin
      admin_password: admin
  tags:
    - ape_grafana

- name: install ape_sqs
  hosts: all
  vars:
    project_path: "{{ lookup('env', 'PWD') }}"
    aws_region: "ap-southeast-1"
    sqs_queue_name: "emr-state-queue"
    exec_exporter_user: "hadoop"
    private_key_file: "{{ lookup('env', 'PWD') }}/emr-key.pem"
  roles:
    - ape_sqs
  tags:
    - ape_sqs