---
- import_tasks: preflight.yml
  tags:
    - jmx_exporter_install
    - jmx_exporter_configure

- import_tasks: install.yml
  become: true
  when:
    ( not __jmx_exporter_is_installed.stat.exists ) or
    ( __jmx_exporter_current_version_output.stdout !=  jmx_exporter_version ) or
    ( jmx_exporter_jar_local_dir | length > 0 )
  tags:
    - jmx_exporter_install

- import_tasks: configure.yml
  become: true
  tags:
    - jmx_exporter_configure

- name: jmx installed and update prometheus_scrape_url
  become: true
  connection: local
  shell: "{{ python_venv_execute }} {{update_scrape_script}} {{ aws_region }} {{ cluster_id }} {{ip_type}} {{prometheus_sd_dir}}"
  when:
   - not ansible_check_mode